In [1]:
import pandas as pd

In [2]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 1. Check first 3 rows

In [4]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

### 2. check last 3 rows

In [5]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### 3. find shape of dataframe (rows, col)

In [6]:
df1.shape

(7, 3)

In [39]:
print(f'Number of Rows is {df1.shape[0]} and Number of Columns is {df1.shape[1]}')

Number of Rows is 7 and Number of Columns is 5

### 4. get information about df

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

### 5. check null values

In [8]:
df1.isna()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [44]:
df1.isna().sum()

Name           0
Marks          0
Gender         0
half_mark      0
Male_female    0
dtype: int64

In [41]:
df1.isna().sum(axis = 0)

Name           0
Marks          0
Gender         0
half_mark      0
Male_female    0
dtype: int64

In [43]:
df1.isna().sum(axis = 1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

### 6. get overall statistics

In [10]:
df1.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [46]:
df1.describe(include= 'all')

           Name      Marks  Gender  half_mark  Male_female
count         7   7.000000       7   7.000000     7.000000
unique        7        NaN       2        NaN          NaN
top     Priyang        NaN  Female        NaN          NaN
freq          1        NaN       4        NaN          NaN
mean        NaN  92.142857     NaN  46.071429     0.571429
std         NaN   6.491753     NaN   3.245877     0.534522
min         NaN  83.000000     NaN  41.500000     0.000000
25%         NaN  88.000000     NaN  44.000000     0.000000
50%         NaN  90.000000     NaN  45.000000     1.000000
75%         NaN  98.500000     NaN  49.250000     1.000000
max         NaN  99.000000     NaN  49.500000     1.000000

In [11]:
df1.groupby("Gender")["Gender"].count()

Gender
Female    4
Male      3
Name: Gender, dtype: int64

### 7. find unique values from gender column

In [12]:
print(df1["Gender"].unique())

['Male' 'Female']

### 8. find no. of unique values from gender column

In [ ]:
len(df1["Gender"].unique())

2

In [48]:
df1["Gender"].nunique()

2

### 9. display count of individual unique values in gender col

In [14]:
df1.groupby("Gender")["Gender"].count()

Gender
Female    4
Male      3
Name: Gender, dtype: int64

In [49]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

### 10. find total no. of students having marks b/w 90 to 100 (inclusive), using between method

In [15]:
df1[(df1["Marks"] >= 90) & (df1["Marks"] <= 100) ]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [50]:
len(df1[(df1["Marks"] >= 90) & (df1["Marks"] <= 100) ])

4

In [16]:
df1[df1["Marks"].between(90, 100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

### 11. find avg marks

In [17]:
df1["Marks"].mean()

np.float64(92.14285714285714)

In [51]:
df1["Marks"].min()

np.int64(83)

### 12. apply method (use to make a new col of half marks)

In [18]:
def half_mark(x):
    return x/2

In [20]:
df1["half_mark"] = df1["Marks"].apply(half_mark)

In [52]:
df1["Marks"].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

### 13. Map function (use to make a new col labelled 'Male_female'; use 1 for male and 0 for female)

In [24]:
df1["Male_female"] = df1["Gender"].map({"Male": 0 , "Female": 1})

In [25]:
df1

      Name  Marks  Gender  half_mark  Male_female
0  Priyang     98    Male       49.0            0
1   Aadhya     89  Female       44.5            1
2   Krisha     99  Female       49.5            1
3   Vedant     87    Male       43.5            0
4   Parshv     90    Male       45.0            0
5   Mittal     83  Female       41.5            1
6  Archana     99  Female       49.5            1

### 14. drop column(s)

In [53]:
df1.drop("half_mark",axis = 1)

      Name  Marks  Gender  Male_female
0  Priyang     98    Male            0
1   Aadhya     89  Female            1
2   Krisha     99  Female            1
3   Vedant     87    Male            0
4   Parshv     90    Male            0
5   Mittal     83  Female            1
6  Archana     99  Female            1

In [54]:
df1

      Name  Marks  Gender  half_mark  Male_female
0  Priyang     98    Male       49.0            0
1   Aadhya     89  Female       44.5            1
2   Krisha     99  Female       49.5            1
3   Vedant     87    Male       43.5            0
4   Parshv     90    Male       45.0            0
5   Mittal     83  Female       41.5            1
6  Archana     99  Female       49.5            1

In [56]:
df1.drop("half_mark",axis = 1, inplace= True)

In [57]:
df1

      Name  Marks  Gender  Male_female
0  Priyang     98    Male            0
1   Aadhya     89  Female            1
2   Krisha     99  Female            1
3   Vedant     87    Male            0
4   Parshv     90    Male            0
5   Mittal     83  Female            1
6  Archana     99  Female            1

### 15. print name of cols

In [28]:
df1.columns

Index(['Name', 'Marks', 'Gender', 'half_mark', 'Male_female'], dtype='object')

In [ ]:
df1.index

RangeIndex(start=0, stop=7, step=1)

### 16. sort by marks

In [31]:
df1.sort_values(by="Marks",  ascending=False)

      Name  Marks  Gender  half_mark  Male_female
2   Krisha     99  Female       49.5            1
6  Archana     99  Female       49.5            1
0  Priyang     98    Male       49.0            0
4   Parshv     90    Male       45.0            0
1   Aadhya     89  Female       44.5            1
3   Vedant     87    Male       43.5            0
5   Mittal     83  Female       41.5            1

In [59]:
df1.sort_values(by=["Marks","Gender"],  ascending=False)

      Name  Marks  Gender  Male_female
2   Krisha     99  Female            1
6  Archana     99  Female            1
0  Priyang     98    Male            0
4   Parshv     90    Male            0
1   Aadhya     89  Female            1
3   Vedant     87    Male            0
5   Mittal     83  Female            1

### 17. display marks and name of female students

In [37]:
df1[["Name","Marks"]][(df1["Gender"] == 'Female')]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99

In [63]:
df1[["Name","Marks"]][df1["Gender"].isin(['Female'])]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99